---
# handlers file for podman_play

- name: Restart podman_play_app
  listen: "restart podman_play_app"
  ansible.builtin.systemd:
    name: "{{ podman_play_pod_name }}.service"
    state: "restarted"
    scope: "user"
    daemon_reload: true
    enabled: true
  become_user: "{{ podman_play_user | default(ansible_user_id) }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ __user_info.uid | default(ansible_user_uid) }}"
